"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='your-secret-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default=[], cast=lambda v: [s.strip() for s in v.split(',')])

SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React app origin
]


PUBLITIO_API_KEY = config('PUBLITIO_API_KEY', default='api key')
PUBLITIO_API_SECRET = config('PUBLITIO_API_SECRET', default='api secret')
ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

from pymongo import MongoClient

# Database - Using pymongo with MongoDB
# Note: pymongo will be used manually to connect to MongoDB in views/models
MONGO_DB_NAME = config('MONGO_DB_NAME')
MONGO_URI = config('MONGO_URI')

# from pymongo import MongoClient
# MONGO_DB = MongoClient("mongodb+srv://datauser:DwEUuX1U4O2CkFvH@cluster0.wmpao.mongodb.net/mydatabase?retryWrites=true&w=majority")
# db = client['dev']  # your database name

# Create a MongoClient to connect to MongoDB
# MONGO_CLIENT = pymongo.MongoClient(MONGO_URI,  serverSelectionTimeoutMS=50000 )
MONGO_CLIENT = MongoClient(MONGO_URI)


# Get the database
MONGO_DB = MONGO_CLIENT[MONGO_DB_NAME]

# settings.py
STRIPE_PUBLIC_KEY = config('STRIPE_PUBLIC_KEY')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY')


from datetime import timedelta

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),  # Token will expire in 24 hours
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),   # Optional: You can also have refresh tokens last for a week
}

#email
SENDGRID_SECRET_KEY = config('SENDGRID_SECRET_KEY')
SENDER_EMAIL = config('SENDER_EMAIL')

key = "api1"
#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

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = key  # Use 'apikey' as the username
EMAIL_HOST_PASSWORD = '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'  # Use the API key you generated
DEFAULT_FROM_EMAIL = 'syedmehrab2288@gmail.com'

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
